[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scraper_leva_padova"
version = "0.0.2"
authors = [{ name = "Uberdev", email = "uber@yomama.com" }]
description = "Scraper for the military conscription archives of Padua and Rovigo provinces, Veneto, Italy"
readme = "README.md"
dependencies = [
    "cachetools",
 "requests",
 "loguru",
 "beautifulsoup4>=4.14.3",
]
requires-python = ">=3.13"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["cli", "controller"]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
leva-cli = "cli:main"
